# Generated by Django 5.0.4 on 2024-04-17 12:10

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=django_jalali.db.models.jDateField(default='1403-01-29'),
        ),
    ]
